import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { FiArrowRight, FiBarChart2, FiCheckCircle, FiCloudRain, FiHelpCircle, FiMapPin, FiMenu, FiShield, FiX } from 'react-icons/fi';

const features = [['Live weather', 'Hyperlocal forecasts and timely weather alerts.', FiCloudRain], ['Mandi intelligence', 'Know prices before you take your produce to market.', FiBarChart2], ['Trusted guidance', 'Crop care, schemes and expert support in one place.', FiShield]];
const faqs = [['Is Kisaan Saathi free to use?', 'Yes. Create your account to access the dashboard and essential farming insights.'], ['Will it work for my location?', 'Yes. Set your village or allow location access for information tailored to your area.'], ['Can I use it on my phone?', 'Absolutely. Kisaan Saathi is built mobile-first and works on any modern browser.']];

export default function LandingPage() {
  const [menu, setMenu] = useState(false); const [open, setOpen] = useState(0);
  return <div className="landing text-slate-800 overflow-x-hidden">
    <header className="landing-nav"><Link to="/" className="brand"><span>🌾</span> Kisaan Saathi</Link><button className="md:hidden" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <FiX /> : <FiMenu />}</button><nav className={menu ? 'open' : ''}><a href="#features">Features</a><a href="#how">How it works</a><a href="#stories">Stories</a><Link to="/login" className="nav-login">Login</Link><Link to="/register" className="nav-cta">Get Started <FiArrowRight /></Link></nav></header>
    <main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><FiMapPin /> Built for India’s farmers</p><h1>Grow every season with <em>clarity.</em></h1><p className="hero-text">One smart companion for weather, mandi prices, crop guidance and government schemes—made for the way you farm.</p><div className="hero-actions"><Link to="/register" className="primary-btn">Get Started <FiArrowRight /></Link><Link to="/login" className="text-btn">I already have an account</Link></div><div className="hero-trust"><span>✓ Free to start</span><span>✓ Local language friendly</span><span>✓ Your data stays yours</span></div></div><div className="hero-visual"><div className="sun"></div><div className="field field-one"></div><div className="field field-two"></div><div className="farmer-card"><img src="https://lh3.googleusercontent.com/aida-public/AB6AXuCD8vxWRzzxmNv-gM3F4Za2EFX5DTDX1_SRcZ0CLxsPN4DcoNbX3hlkvlFAUco0iYbk6AzaLSEqMMzedhaIEPvePBIp41GU5sVcRADnQSgPkxbX52F9XZe-AtoXP6sHAP-F0S9c1s8Aj_3Dj4W0E-Kse66IAXSEDldz4HMDBvNfX_27VV6AG1KFI-ESaB-IP9MsD9M8EOh3Go5Suij5grrQIELk10YgeqmM3Qglwzbe_cSNZ8K-xZGFayh9_BLfB6Qsn5jql_wxrmg " alt="Farmer in a green field" /><div><small>Today in your farm</small><strong>28° · Partly cloudy</strong><span>Perfect time for field work</span></div></div><div className="price-card"><FiBarChart2 /><div><small>Wheat mandi price</small><strong>₹2,410 / quintal</strong><span className="up">↗ 4.2% this week</span></div></div></div></section>
      <section className="logo-strip"><span>Weather alerts</span><span>Mandi prices</span><span>Crop care</span><span>Govt. schemes</span><span>Community</span></section>
      <section id="features" className="section"><p className="eyebrow centered">Everything that matters</p><h2>Your farm, informed at every step.</h2><p className="section-intro">Simple tools, practical advice and the information you need—right when you need it.</p><div className="feature-grid">{features.map(([title, desc, Icon]) => <article className="feature-card" key={title}><div className="icon-wrap"><Icon /></div><h3>{title}</h3><p>{desc}</p><Link to="/register">Explore more <FiArrowRight /></Link></article>)}</div></section>
      <section className="benefit-band"><div><p className="eyebrow">Farming feels better together</p><h2>Less uncertainty.<br />More confident decisions.</h2></div><div className="benefit-list">{['Plan activities around weather windows', 'Compare local mandi rates at a glance', 'Discover schemes you may be eligible for', 'Get crop-care support in your pocket'].map(item => <p key={item}><FiCheckCircle />{item}</p>)}</div></section>
      <section id="how" className="section how"><p className="eyebrow centered">Easy from day one</p><h2>Start farming smarter in minutes.</h2><div className="steps">{[['01','Create your account','Tell us a little about your farm and preferred location.'],['02','Personalize your feed','Choose crops and enable the updates you care about.'],['03','Make better moves','Open your dashboard for your daily farming brief.']].map(([no,title,text]) => <article key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="screenshots"><div><p className="eyebrow">A calm, clear dashboard</p><h2>All your essentials,<br />beautifully organized.</h2><p>Designed to make useful information feel effortless—whether you’re at home or in the field.</p><Link to="/register" className="primary-btn">See your dashboard <FiArrowRight /></Link></div><div className="dashboard-shot"><div className="shot-top"><b>🌾 Kisaan Saathi</b><span>Madhepura, Bihar</span></div><div className="shot-grid"><div className="weather-shot"><small>WEATHER TODAY</small><strong>28°</strong><span>Partly cloudy · feels 31°</span></div><div className="mandi-shot"><small>MANDI PRICES</small><p>Wheat <b>₹2,410</b></p><p>Paddy <b>₹2,180</b></p></div><div className="tip-shot"><small>CROP TIP</small><p>Check soil moisture before irrigation today.</p></div></div></div></section>
      <section id="stories" className="section testimonials"><p className="eyebrow centered">From the community</p><h2>Trusted by farmers, every day.</h2><div className="quote-grid"><blockquote>“The mandi price updates help me decide when to sell. It has made a real difference for my family.”<footer>Ramesh Kumar <span>· Paddy farmer, Bihar</span></footer></blockquote><blockquote>“I never miss a weather change now. Kisaan Saathi is the first thing I check in the morning.”<footer>Sunita Devi <span>· Vegetable farmer, Uttar Pradesh</span></footer></blockquote></div></section>
      <section className="section faq"><p className="eyebrow centered">Questions, answered</p><h2>Good to know.</h2>{faqs.map(([q,a], i) => <div className="faq-row" key={q}><button onClick={() => setOpen(open === i ? -1 : i)}>{q}<FiHelpCircle /></button>{open === i && <p>{a}</p>}</div>)}</section>
      <section id="contact" className="contact"><div><p className="eyebrow">Your next season starts here</p><h2>Give your farm a smarter companion.</h2><p>Create your free account and see what’s possible.</p></div><Link to="/register" className="light-btn">Get Started <FiArrowRight /></Link></section>
    </main><footer className="landing-footer"><div className="brand"><span>🌾</span> Kisaan Saathi</div><p>Made with care for India’s farming community.</p><Link to="/login">Login</Link></footer>
  </div>;
}
